PeopleRegistrationSystem/PeopleRegistrationSystem/Controllers/DashboardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PeopleRegistrationSystem.Models;
using PeopleRegistrationSystem.ViewModels;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace PeopleRegistrationSystem.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IHttpContextAccessor contxt;

        private AppDbContext _context;

        private readonly IMapper _mapper;

        public DashboardController(AppDbContext context, IMapper mapper, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;

            _mapper = mapper;

            contxt = httpContextAccessor;
        }
        public IActionResult Index()
        {

            var scholarships = _context.Users.ToList();

            return View(_mapper.Map<List<UserViewModel>>(scholarships));
            
        }

        public IActionResult removeUser(int id)
        {
            var scholarship = _context.Users.Find(id);

            _context.Users.Remove(scholarship);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult updateUser(int id)
        {
            var scholarship = _context.Users.Find(id);

            ViewBag.EducationLevelSelect = new SelectList(new List<EducationLevelSelectList>()
            {
                new(){Data="Primary Education", Value="Primary Education"},
                new(){Data="Secondary Education", Value="Secondary Education"},
                new(){Data="High School", Value="High School"},
                new(){Data="Bachelor's Degree", Value="Bachelor's Degree"},
                new(){Data="Master Degree", Value="Master Degree"},
                new(){Data="PhD", Value="PhD"},


            }, "Value", "Data");//view Data to user
            return View(_mapper.Map<UserViewModel>(scholarship));
        }

        [HttpPost]
        public IActionResult updateUser(UserViewModel updateScholarship)
        {
            IActionResult result = null;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Users.Update(_mapper.Map<User>(updateScholarship));

                    _context.SaveChanges();

                    TempData["status"] = "User successfully updated.";

                    return RedirectToAction("Index");
                }
                catch (Exception)
                {

                    result = View();
                }

            }
            else
            {
                result = View();

            }

            ViewBag.EducationLevelSelect = new SelectList(new List<EducationLevelSelectList>()
                {
                    new(){Data="Primary Education", Value="Primary Education"},
                    new(){Data="Secondary Education", Value="Secondary Education"},
                    new(){Data="High School", Value="High School"},
                    new(){Data="Bachelor's Degree", Value="Bachelor's Degree"},
                    new(){Data="Master Degree", Value="Master Degree"},
                    new(){Data="PhD", Value="PhD"},


                }, "Value", "Data");//view Data to user

            return result;
        }
    }
}

PeopleRegistrationSystem/PeopleRegistrationSystem/Controllers/RegisterController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using PeopleRegistrationSystem.Models;
using PeopleRegistrationSystem.ViewModels;

namespace PeopleRegistrationSystem.Controllers
{
    public class RegisterController : Controller
    {
        private AppDbContext _context;

        private readonly IMapper _mapper;

        public RegisterController(AppDbContext context, IMapper mapper)
        {
            _context = context;

            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]//Default
        public IActionResult userRegister()
        {
            // Create a select list for education levels
            ViewBag.EducationLevelSelectUser = new SelectList(new List<EducationLevelSelectList>()
            {
                new(){Data="Primary Education", Value="Primary Education"},
                new(){Data="Secondary Education", Value="Secondary Education"},
                new(){Data="High School", Value="High School"},
                new(){Data="Bachelor's Degree", Value="Bachelor's Degree"},
                new(){Data="Master Degree", Value="Master Degree"},
                new(){Data="PhD", Value="PhD"},



            }, "Value", "Data");//view Data to who make registeration

            return View();
        }

        [HttpPost]
        public IActionResult userRegister(UserViewModel newUser)
        {
            IActionResult result = null;
            // Create a select list for education levels
            ViewBag.EducationLevelSelectUser = new SelectList(new List<EducationLevelSelectList>()
                {
                    new(){Data="Primary Education", Value="Primary Education"},
                    new(){Data="Secondary Education", Value="Secondary Education"},
                    new(){Data="High School", Value="High School"},
                    new(){Data="Bachelor's Degree", Value="Bachelor's Degree"},
                    new(){Data="Master Degree", Value="Master Degree"},
                    new(){Data="PhD", Value="PhD"},

                }, "Value", "Data");//view Data to who make registiration

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Users.Add(_mapper.Map<User>(newUser));

                    _context.SaveChanges();

                    TempData["status"] = "User successfully registered.";

                    return RedirectToAction("Index", "Home");
                }
                catch (Exception ex)
                {
                    // Check if the exception is due to a unique key violation (duplicate email & identification num.)
                    if (ex.InnerException is SqlException sqlException )
                    {
                        if (sqlException.Message.Contains("Cannot insert duplicate key row") &&
        sqlException.Message.Contains("IX_User_Email"))
                        {
                            TempData["status"] = "Email is already registered.";
                        }
                        else if(sqlException.Message.Contains("Cannot insert duplicate key row") &&
        sqlException.Message.Contains("IX_User_Identification"))
                        {
                            TempData["status"] = "Idetification number is already registered.";
                        }
                        
                    }
                    else
                    {
                        // Handle other exceptions
                        TempData["status"] = "An error occurred while registering the user.";
                    }
                    return View();
                }
            }
            else
            {
                result = View();
            }
            return result;
        }

    }
}

PeopleRegistrationSystem/PeopleRegistrationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleRegistrationSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeopleRegistrationSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3" >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeopleRegistrationSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="userRegister">Register User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    @if (@TempData["status"] != null)
    {
        <div class="alert alert-info" role="alert" style="width: 1300px; margin-left:150px">
            @TempData["status"]
        </div>
    }

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PeopleRegistrationSystem - <a asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>